// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniShop.Data;

#nullable disable

namespace MiniShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331044653_AddRating")]
    partial class AddRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("MiniShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothes"
                        });
                });

            modelBuilder.Entity("MiniShop.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MiniShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MiniShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MiniShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book01.png",
                            Name = "Clean Code",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book02.png",
                            Name = "The Pragmatic Programmer",
                            Price = 14.90m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book03.png",
                            Name = "Refactoring",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book04.png",
                            Name = "Design Patterns",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book05.png",
                            Name = "Domain-Driven Design",
                            Price = 22.50m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book06.png",
                            Name = "You Don't Know JS",
                            Price = 11.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book07.png",
                            Name = "Eloquent JavaScript",
                            Price = 10.50m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book08.png",
                            Name = "C# in Depth",
                            Price = 16.80m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book09.png",
                            Name = "ASP.NET Core in Action",
                            Price = 17.25m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book10.png",
                            Name = "Head First Design Patterns",
                            Price = 15.75m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book11.png",
                            Name = "The Clean Coder",
                            Price = 12.90m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            ImageUrl = "/images/products/book12.png",
                            Name = "Working Effectively with Legacy Code",
                            Price = 19.40m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes01.png",
                            Name = "T-Shirt Basic",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes02.png",
                            Name = "Oversized T-Shirt",
                            Price = 11.50m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes03.png",
                            Name = "Hoodie Zip",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes04.png",
                            Name = "Hoodie Pullover",
                            Price = 18.50m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes05.png",
                            Name = "Jeans Slim Fit",
                            Price = 24.90m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes06.png",
                            Name = "Jeans Regular",
                            Price = 23.50m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes07.png",
                            Name = "Chino Pants",
                            Price = 21.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes08.png",
                            Name = "Jacket Denim",
                            Price = 29.90m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes09.png",
                            Name = "Jacket Bomber",
                            Price = 32.00m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes10.png",
                            Name = "Sweater Knit",
                            Price = 16.90m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes11.png",
                            Name = "Shorts Casual",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes12.png",
                            Name = "Polo Shirt",
                            Price = 13.90m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            ImageUrl = "/images/products/clothes13.png",
                            Name = "Cap Classic",
                            Price = 7.50m
                        });
                });

            modelBuilder.Entity("MiniShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@minishop.local",
                            FullName = "MiniShop Admin",
                            PasswordHash = "$2a$11$B5/5dAfC590OCcEeZubh4OlYDcTN20fBrianL467QfwzMaw.7so6a",
                            Role = "Admin",
                            Status = 0
                        });
                });

            modelBuilder.Entity("MiniShop.Models.Comment", b =>
                {
                    b.HasOne("MiniShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniShop.Models.Order", b =>
                {
                    b.HasOne("MiniShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniShop.Models.OrderItem", b =>
                {
                    b.HasOne("MiniShop.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniShop.Models.Product", b =>
                {
                    b.HasOne("MiniShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniShop.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
